export const countryCodes = [
  // High-priority countries
  { a3: "VNM", value: "84", label: "Vietnam", flag: "🇻🇳" },
  { a3: "USA", value: "1", label: "United States", flag: "🇺🇸" },
  { a3: "GBR", value: "44", label: "United Kingdom", flag: "🇬🇧" },
  // Rest follows
  { a3: "AFG", value: "93", label: "Afghanistan", flag: "🇦🇫" },
  { a3: "ALB", value: "355", label: "Albania", flag: "🇦🇱" },
  { a3: "DZA", value: "213", label: "Algeria", flag: "🇩🇿" },
  { a3: "ASM", value: "684", label: "American Samoa", flag: "🇦🇸" },
  { a3: "AND", value: "376", label: "Andorra", flag: "🇦🇩" },
  { a3: "AGO", value: "244", label: "Angola", flag: "🇦🇴" },
  { a3: "AIA", value: "264", label: "Anguilla", flag: "🇦🇮" },
  { a3: "ATA", value: "672", label: "Antarctica", flag: "🇦🇶" },
  { a3: "ATG", value: "268", label: "Antigua and Barbuda", flag: "🇦🇬" },
  { a3: "ARG", value: "54", label: "Argentina", flag: "🇦🇷" },
  { a3: "ARM", value: "374", label: "Armenia", flag: "🇦🇲" },
  { a3: "ABW", value: "297", label: "Aruba", flag: "🇦🇼" },
  { a3: "AUS", value: "61", label: "Australia", flag: "🇦🇺" },
  { a3: "AUT", value: "43", label: "Austria", flag: "🇦🇹" },
  { a3: "AZE", value: "994", label: "Azerbaijan", flag: "🇦🇿" },
  { a3: "BHS", value: "242", label: "Bahamas", flag: "🇧🇸" },
  { a3: "BHR", value: "973", label: "Bahrain", flag: "🇧🇭" },
  { a3: "BGD", value: "880", label: "Bangladesh", flag: "🇧🇩" },
  { a3: "BRB", value: "246", label: "Barbados", flag: "🇧🇧" },
  { a3: "BLR", value: "375", label: "Belarus", flag: "🇧🇾" },
  { a3: "BEL", value: "32", label: "Belgium", flag: "🇧🇪" },
  { a3: "BLZ", value: "501", label: "Belize", flag: "🇧🇿" },
  { a3: "BEN", value: "229", label: "Benin", flag: "🇧🇯" },
  { a3: "BMU", value: "441", label: "Bermuda", flag: "🇧🇲" },
  { a3: "BTN", value: "975", label: "Bhutan", flag: "🇧🇹" },
  { a3: "BOL", value: "591", label: "Bolivia", flag: "🇧🇴" },
  { a3: "BES", value: "599", label: "Bonaire", flag: "🇧🇶" },
  { a3: "BIH", value: "387", label: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { a3: "BWA", value: "267", label: "Botswana", flag: "🇧🇼" },
  { a3: "BVT", value: "47", label: "Bouvet Island", flag: "🇧🇻" },
  { a3: "BRA", value: "55", label: "Brazil", flag: "🇧🇷" },
  { a3: "IOT", value: "246", label: "British Indian Ocean Territory", flag: "🇮🇴" },
  { a3: "BRN", value: "673", label: "Brunei Darussalam", flag: "🇧🇳" },
  { a3: "BGR", value: "359", label: "Bulgaria", flag: "🇧🇬" },
  { a3: "BFA", value: "226", label: "Burkina Faso", flag: "🇧🇫" },
  { a3: "BDI", value: "257", label: "Burundi", flag: "🇧🇮" },
  { a3: "KHM", value: "855", label: "Cambodia", flag: "🇰🇭" },
  { a3: "CMR", value: "237", label: "Cameroon", flag: "🇨🇲" },
  { a3: "CAN", value: "1", label: "Canada", flag: "🇨🇦" },
  { a3: "CPV", value: "238", label: "Cape Verde", flag: "🇨🇻" },
  { a3: "CYM", value: "345", label: "Cayman Islands", flag: "🇰🇾" },
  { a3: "CAF", value: "236", label: "Central African Republic", flag: "🇨🇫" },
  { a3: "TCD", value: "235", label: "Chad", flag: "🇹🇩" },
  { a3: "CHL", value: "56", label: "Chile", flag: "🇨🇱" },
  { a3: "CHN", value: "86", label: "China", flag: "🇨🇳" },
  { a3: "CXR", value: "61", label: "Christmas Island", flag: "🇨🇽" },
  { a3: "CCK", value: "61", label: "Cocos (Keeling) Islands", flag: "🇨🇨" },
  { a3: "COL", value: "57", label: "Colombia", flag: "🇨🇴" },
  { a3: "COM", value: "269", label: "Comoros", flag: "🇰🇲" },
  { a3: "COG", value: "242", label: "Congo", flag: "🇨🇬" },
  { a3: "COD", value: "243", label: "Democratic Republic of the Congo", flag: "🇨🇩" },
  { a3: "COK", value: "682", label: "Cook Islands", flag: "🇨🇰" },
  { a3: "CRI", value: "506", label: "Costa Rica", flag: "🇨🇷" },
  { a3: "HRV", value: "385", label: "Croatia", flag: "🇭🇷" },
  { a3: "CUB", value: "53", label: "Cuba", flag: "🇨🇺" },
  { a3: "CUW", value: "599", label: "Curacao", flag: "🇨🇼" },
  { a3: "CYP", value: "357", label: "Cyprus", flag: "🇨🇾" },
  { a3: "CZE", value: "420", label: "Czech Republic", flag: "🇨🇿" },
  { a3: "CIV", value: "225", label: "Cote d'Ivoire", flag: "🇨🇮" },
  { a3: "DNK", value: "45", label: "Denmark", flag: "🇩🇰" },
  { a3: "DJI", value: "253", label: "Djibouti", flag: "🇩🇯" },
  { a3: "DMA", value: "767", label: "Dominica", flag: "🇩🇲" },
  { a3: "DOM", value: "849", label: "Dominican Republic", flag: "🇩🇴" },
  { a3: "ECU", value: "593", label: "Ecuador", flag: "🇪🇨" },
  { a3: "EGY", value: "20", label: "Egypt", flag: "🇪🇬" },
  { a3: "SLV", value: "503", label: "El Salvador", flag: "🇸🇻" },
  { a3: "GNQ", value: "240", label: "Equatorial Guinea", flag: "🇬🇶" },
  { a3: "ERI", value: "291", label: "Eritrea", flag: "🇪🇷" },
  { a3: "EST", value: "372", label: "Estonia", flag: "🇪🇪" },
  { a3: "ETH", value: "251", label: "Ethiopia", flag: "🇪🇹" },
  { a3: "FLK", value: "500", label: "Falkland Islands (Malvinas)", flag: "🇫🇰" },
  { a3: "FRO", value: "298", label: "Faroe Islands", flag: "🇫🇴" },
  { a3: "FJI", value: "679", label: "Fiji", flag: "🇫🇯" },
  { a3: "FIN", value: "358", label: "Finland", flag: "🇫🇮" },
  { a3: "FRA", value: "33", label: "France", flag: "🇫🇷" },
  { a3: "GUF", value: "594", label: "French Guiana", flag: "🇬🇫" },
  { a3: "PYF", value: "689", label: "French Polynesia", flag: "🇵🇫" },
  { a3: "ATF", value: "262", label: "French Southern Territories", flag: "🇹🇫" },
  { a3: "GAB", value: "241", label: "Gabon", flag: "🇬🇦" },
  { a3: "GMB", value: "220", label: "Gambia", flag: "🇬🇲" },
  { a3: "GEO", value: "995", label: "Georgia", flag: "🇬🇪" },
  { a3: "DEU", value: "49", label: "Germany", flag: "🇩🇪" },
  { a3: "GHA", value: "233", label: "Ghana", flag: "🇬🇭" },
  { a3: "GIB", value: "350", label: "Gibraltar", flag: "🇬🇮" },
  { a3: "GRC", value: "30", label: "Greece", flag: "🇬🇷" },
  { a3: "GRL", value: "299", label: "Greenland", flag: "🇬🇱" },
  { a3: "GRD", value: "473", label: "Grenada", flag: "🇬🇩" },
  { a3: "GLP", value: "590", label: "Guadeloupe", flag: "🇬🇵" },
  { a3: "GUM", value: "671", label: "Guam", flag: "🇬🇺" },
  { a3: "GTM", value: "502", label: "Guatemala", flag: "🇬🇹" },
  { a3: "GGY", value: "44", label: "Guernsey", flag: "🇬🇬" },
  { a3: "GIN", value: "224", label: "Guinea", flag: "🇬🇳" },
  { a3: "GNB", value: "245", label: "Guinea-Bissau", flag: "🇬🇼" },
  { a3: "GUY", value: "592", label: "Guyana", flag: "🇬🇾" },
  { a3: "HTI", value: "509", label: "Haiti", flag: "🇭🇹" },
  { a3: "HMD", value: "672", label: "Heard Island and McDonald Islands", flag: "🇭🇲" },
  { a3: "VAT", value: "379", label: "Holy See (Vatican City State)", flag: "🇻🇦" },
  { a3: "HND", value: "504", label: "Honduras", flag: "🇭🇳" },
  { a3: "HKG", value: "852", label: "Hong Kong", flag: "🇭🇰" },
  { a3: "HUN", value: "36", label: "Hungary", flag: "🇭🇺" },
  { a3: "ISL", value: "354", label: "Iceland", flag: "🇮🇸" },
  { a3: "IND", value: "91", label: "India", flag: "🇮🇳" },
  { a3: "IDN", value: "62", label: "Indonesia", flag: "🇮🇩" },
  { a3: "IRN", value: "98", label: "Iran, Islamic Republic of", flag: "🇮🇷" },
  { a3: "IRQ", value: "964", label: "Iraq", flag: "🇮🇶" },
  { a3: "IRL", value: "353", label: "Ireland", flag: "🇮🇪" },
  { a3: "IMN", value: "44", label: "Isle of Man", flag: "🇮🇲" },
  { a3: "ISR", value: "972", label: "Israel", flag: "🇮🇱" },
  { a3: "ITA", value: "39", label: "Italy", flag: "🇮🇹" },
  { a3: "JAM", value: "876", label: "Jamaica", flag: "🇯🇲" },
  { a3: "JPN", value: "81", label: "Japan", flag: "🇯🇵" },
  { a3: "JEY", value: "44", label: "Jersey", flag: "🇯🇪" },
  { a3: "JOR", value: "962", label: "Jordan", flag: "🇯🇴" },
  { a3: "KAZ", value: "7", label: "Kazakhstan", flag: "🇰🇿" },
  { a3: "KEN", value: "254", label: "Kenya", flag: "🇰🇪" },
  { a3: "KIR", value: "686", label: "Kiribati", flag: "🇰🇮" },
  { a3: "PRK", value: "850", label: "Korea, Democratic People's Republic of", flag: "🇰🇵" },
  { a3: "KOR", value: "82", label: "Korea, Republic of", flag: "🇰🇷" },
  { a3: "KWT", value: "965", label: "Kuwait", flag: "🇰🇼" },
  { a3: "KGZ", value: "996", label: "Kyrgyzstan", flag: "🇰🇬" },
  { a3: "LAO", value: "856", label: "Lao People's Democratic Republic", flag: "🇱🇦" },
  { a3: "LVA", value: "371", label: "Latvia", flag: "🇱🇻" },
  { a3: "LBN", value: "961", label: "Lebanon", flag: "🇱🇧" },
  { a3: "LSO", value: "266", label: "Lesotho", flag: "🇱🇸" },
  { a3: "LBR", value: "231", label: "Liberia", flag: "🇱🇷" },
  { a3: "LBY", value: "218", label: "Libya", flag: "🇱🇾" },
  { a3: "LIE", value: "423", label: "Liechtenstein", flag: "🇱🇮" },
  { a3: "LTU", value: "370", label: "Lithuania", flag: "🇱🇹" },
  { a3: "LUX", value: "352", label: "Luxembourg", flag: "🇱🇺" },
  { a3: "MAC", value: "853", label: "Macao", flag: "🇲🇴" },
  { a3: "MKD", value: "389", label: "Macedonia, the Former Yugoslav Republic of", flag: "🇲🇰" },
  { a3: "MDG", value: "261", label: "Madagascar", flag: "🇲🇬" },
  { a3: "MWI", value: "265", label: "Malawi", flag: "🇲🇼" },
  { a3: "MYS", value: "60", label: "Malaysia", flag: "🇲🇾" },
  { a3: "MDV", value: "960", label: "Maldives", flag: "🇲🇻" },
  { a3: "MLI", value: "223", label: "Mali", flag: "🇲🇱" },
  { a3: "MLT", value: "356", label: "Malta", flag: "🇲🇹" },
  { a3: "MHL", value: "692", label: "Marshall Islands", flag: "🇲🇭" },
  { a3: "MTQ", value: "596", label: "Martinique", flag: "🇲🇶" },
  { a3: "MRT", value: "222", label: "Mauritania", flag: "🇲🇷" },
  { a3: "MUS", value: "230", label: "Mauritius", flag: "🇲🇺" },
  { a3: "MYT", value: "262", label: "Mayotte", flag: "🇾🇹" },
  { a3: "MEX", value: "52", label: "Mexico", flag: "🇲🇽" },
  { a3: "FSM", value: "691", label: "Micronesia, Federated States of", flag: "🇫🇲" },
  { a3: "MDA", value: "373", label: "Moldova, Republic of", flag: "🇲🇩" },
  { a3: "MCO", value: "377", label: "Monaco", flag: "🇲🇨" },
  { a3: "MNG", value: "976", label: "Mongolia", flag: "🇲🇳" },
  { a3: "MNE", value: "382", label: "Montenegro", flag: "🇲🇪" },
  { a3: "MSR", value: "664", label: "Montserrat", flag: "🇲🇸" },
  { a3: "MAR", value: "212", label: "Morocco", flag: "🇲🇦" },
  { a3: "MOZ", value: "258", label: "Mozambique", flag: "🇲🇿" },
  { a3: "MMR", value: "95", label: "Myanmar", flag: "🇲🇲" },
  { a3: "NAM", value: "264", label: "Namibia", flag: "🇳🇦" },
  { a3: "NRU", value: "674", label: "Nauru", flag: "🇳🇷" },
  { a3: "NPL", value: "977", label: "Nepal", flag: "🇳🇵" },
  { a3: "NLD", value: "31", label: "Netherlands", flag: "🇳🇱" },
  { a3: "NCL", value: "687", label: "New Caledonia", flag: "🇳🇨" },
  { a3: "NZL", value: "64", label: "New Zealand", flag: "🇳🇿" },
  { a3: "NIC", value: "505", label: "Nicaragua", flag: "🇳🇮" },
  { a3: "NER", value: "227", label: "Niger", flag: "🇳🇪" },
  { a3: "NGA", value: "234", label: "Nigeria", flag: "🇳🇬" },
  { a3: "NIU", value: "683", label: "Niue", flag: "🇳🇺" },
  { a3: "NFK", value: "672", label: "Norfolk Island", flag: "🇳🇫" },
  { a3: "MNP", value: "670", label: "Northern Mariana Islands", flag: "🇲🇵" },
  { a3: "NOR", value: "47", label: "Norway", flag: "🇳🇴" },
  { a3: "OMN", value: "968", label: "Oman", flag: "🇴🇲" },
  { a3: "PAK", value: "92", label: "Pakistan", flag: "🇵🇰" },
  { a3: "PLW", value: "680", label: "Palau", flag: "🇵🇼" },
  { a3: "PSE", value: "970", label: "Palestine, State of", flag: "🇵🇸" },
  { a3: "PAN", value: "507", label: "Panama", flag: "🇵🇦" },
  { a3: "PNG", value: "675", label: "Papua New Guinea", flag: "🇵🇬" },
  { a3: "PRY", value: "595", label: "Paraguay", flag: "🇵🇾" },
  { a3: "PER", value: "51", label: "Peru", flag: "🇵🇪" },
  { a3: "PHL", value: "63", label: "Philippines", flag: "🇵🇭" },
  { a3: "PCN", value: "870", label: "Pitcairn", flag: "🇵🇳" },
  { a3: "POL", value: "48", label: "Poland", flag: "🇵🇱" },
  { a3: "PRT", value: "351", label: "Portugal", flag: "🇵🇹" },
  { a3: "PRI", value: "1", label: "Puerto Rico", flag: "🇵🇷" },
  { a3: "QAT", value: "974", label: "Qatar", flag: "🇶🇦" },
  { a3: "ROU", value: "40", label: "Romania", flag: "🇷🇴" },
  { a3: "RUS", value: "7", label: "Russian Federation", flag: "🇷🇺" },
  { a3: "RWA", value: "250", label: "Rwanda", flag: "🇷🇼" },
  { a3: "REU", value: "262", label: "Reunion", flag: "🇷🇪" },
  { a3: "BLM", value: "590", label: "Saint Barthelemy", flag: "🇧🇱" },
  { a3: "SHN", value: "290", label: "Saint Helena", flag: "🇸🇭" },
  { a3: "KNA", value: "869", label: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { a3: "LCA", value: "758", label: "Saint Lucia", flag: "🇱🇨" },
  { a3: "MAF", value: "590", label: "Saint Martin (French part)", flag: "🇲🇫" },
  { a3: "SPM", value: "508", label: "Saint Pierre and Miquelon", flag: "🇵🇲" },
  { a3: "VCT", value: "784", label: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { a3: "WSM", value: "685", label: "Samoa", flag: "🇼🇸" },
  { a3: "SMR", value: "378", label: "San Marino", flag: "🇸🇲" },
  { a3: "STP", value: "239", label: "Sao Tome and Principe", flag: "🇸🇹" },
  { a3: "SAU", value: "966", label: "Saudi Arabia", flag: "🇸🇦" },
  { a3: "SEN", value: "221", label: "Senegal", flag: "🇸🇳" },
  { a3: "SRB", value: "381", label: "Serbia", flag: "🇷🇸" },
  { a3: "SYC", value: "248", label: "Seychelles", flag: "🇸🇨" },
  { a3: "SLE", value: "232", label: "Sierra Leone", flag: "🇸🇱" },
  { a3: "SGP", value: "65", label: "Singapore", flag: "🇸🇬" },
  { a3: "SXM", value: "721", label: "Sint Maarten (Dutch part)", flag: "🇸🇽" },
  { a3: "SVK", value: "421", label: "Slovakia", flag: "🇸🇰" },
  { a3: "SVN", value: "386", label: "Slovenia", flag: "🇸🇮" },
  { a3: "SLB", value: "677", label: "Solomon Islands", flag: "🇸🇧" },
  { a3: "SOM", value: "252", label: "Somalia", flag: "🇸🇴" },
  { a3: "ZAF", value: "27", label: "South Africa", flag: "🇿🇦" },
  { a3: "SGS", value: "500", label: "South Georgia and the South Sandwich Islands", flag: "🇬🇸" },
  { a3: "SSD", value: "211", label: "South Sudan", flag: "🇸🇸" },
  { a3: "ESP", value: "34", label: "Spain", flag: "🇪🇸" },
  { a3: "LKA", value: "94", label: "Sri Lanka", flag: "🇱🇰" },
  { a3: "SDN", value: "249", label: "Sudan", flag: "🇸🇩" },
  { a3: "SUR", value: "597", label: "Suriname", flag: "🇸🇷" },
  { a3: "SJM", value: "47", label: "Svalbard and Jan Mayen", flag: "🇸🇯" },
  { a3: "SWZ", value: "268", label: "Swaziland", flag: "🇸🇿" },
  { a3: "SWE", value: "46", label: "Sweden", flag: "🇸🇪" },
  { a3: "CHE", value: "41", label: "Switzerland", flag: "🇨🇭" },
  { a3: "SYR", value: "963", label: "Syrian Arab Republic", flag: "🇸🇾" },
  { a3: "TWN", value: "886", label: "Taiwan", flag: "🇹🇼" },
  { a3: "TJK", value: "992", label: "Tajikistan", flag: "🇹🇯" },
  { a3: "TZA", value: "255", label: "United Republic of Tanzania", flag: "🇹🇿" },
  { a3: "THA", value: "66", label: "Thailand", flag: "🇹🇭" },
  { a3: "TLS", value: "670", label: "Timor-Leste", flag: "🇹🇱" },
  { a3: "TGO", value: "228", label: "Togo", flag: "🇹🇬" },
  { a3: "TKL", value: "690", label: "Tokelau", flag: "🇹🇰" },
  { a3: "TON", value: "676", label: "Tonga", flag: "🇹🇴" },
  { a3: "TTO", value: "868", label: "Trinidad and Tobago", flag: "🇹🇹" },
  { a3: "TUN", value: "216", label: "Tunisia", flag: "🇹🇳" },
  { a3: "TUR", value: "90", label: "Turkey", flag: "🇹🇷" },
  { a3: "TKM", value: "993", label: "Turkmenistan", flag: "🇹🇲" },
  { a3: "TCA", value: "649", label: "Turks and Caicos Islands", flag: "🇹🇨" },
  { a3: "TUV", value: "688", label: "Tuvalu", flag: "🇹🇻" },
  { a3: "UGA", value: "256", label: "Uganda", flag: "🇺🇬" },
  { a3: "UKR", value: "380", label: "Ukraine", flag: "🇺🇦" },
  { a3: "ARE", value: "971", label: "United Arab Emirates", flag: "🇦🇪" },
  { a3: "UMI", value: "1", label: "United States Minor Outlying Islands", flag: "🇺🇲" },
  { a3: "URY", value: "598", label: "Uruguay", flag: "🇺🇾" },
  { a3: "UZB", value: "998", label: "Uzbekistan", flag: "🇺🇿" },
  { a3: "VUT", value: "678", label: "Vanuatu", flag: "🇻🇺" },
  { a3: "VEN", value: "58", label: "Venezuela", flag: "🇻🇪" },
  { a3: "VGB", value: "284", label: "British Virgin Islands", flag: "🇻🇬" },
  { a3: "VIR", value: "340", label: "US Virgin Islands", flag: "🇻🇮" },
  { a3: "WLF", value: "681", label: "Wallis and Futuna", flag: "🇼🇫" },
  { a3: "ESH", value: "212", label: "Western Sahara", flag: "🇪🇭" },
  { a3: "YEM", value: "967", label: "Yemen", flag: "🇾🇪" },
  { a3: "ZMB", value: "260", label: "Zambia", flag: "🇿🇲" },
  { a3: "ZWE", value: "263", label: "Zimbabwe", flag: "🇿🇼" },
];